name: Build and Test Shopping app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install npm dependencies
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "sdplamen"
  run-ui-tests:
    runs-on: ubuntu-latest
    needs: build_CI
    steps:
    - name: Install NPM dependen
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Install Playwirght Browsers
      run: npx playwright install
    - name: Start the Aplication
      run: npm start &
    - name: Run UI tests
      run: npm run test:ui
    - name: Display softuni username
      run: echo "sdplamen"
  deploy-production:
    needs: run-ui-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          
